groups:
  - name: all
    jobs:
      - terraform-apply
resources:
  - name: git_stack_ansible
    type: git
    source:
      branch: stacks
      private_key: ((shefali_git.ssh_key))
      uri: git@github.com:singhal092/shefali_cycloid_testing.git
    check_every: 1m  
resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: 0.12.6
jobs:
  - name: terraform-apply
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - do:  
          - get: git_stack_ansible
          - task: run_terraform_apply
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: mvohra447/terraform-runner
                  tag: latest
              container_limits: {}
              run:
                path: /bin/bash
                args:
                  - '-c'
                  - |
                    cd cloned
                    ls -ltr
                    #terraform 0.13upgrade -yes
                    #terraform init
                    #terraform plan
                    #terraform apply --auto-approve
              inputs:
                - name: git_stack_ansible
                  path: cloned
