version: "2"
name: deepak-testing
canonical: deepak-testing
author: root cycloid
status: private
description: demonstration
image: ""
keywords:
- security
- provider:aws
technologies:
- technology: stackcraft
  version: "1"
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
    terraform:
      deepak-testing:
        destination: ($ project $)/terraform/($ environment $)/deepak-testing.tf
        path: terraform/default/deepak-testing.tf.sample
